name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  ci: 
    runs-on : ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies 
        run: pip install -r requirements.txt

      - name: Linter with Ruff
        run: ruff check devchain 